FlowGestaoContrato/Controllers/ProcessoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FlowGestaoContrato.Interfaces;
using FlowGestaoContrato.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FlowGestaoContrato.Controllers
{
    public class ProcessoController : Controller
    {
        private readonly IProcessoRepositorio _processoRepositorio;
        private readonly IUsuarioRepositorio _usuarioRepositorio;

        public ProcessoController(IProcessoRepositorio processoRepositorio, IUsuarioRepositorio usuarioRepositorio)
        {
            _processoRepositorio = processoRepositorio;
            _usuarioRepositorio = usuarioRepositorio;
        }

        [Authorize(Roles = "Administrador,Fornecedor")]
        public IActionResult Index()
        {
            string id=string.Empty ;
            if (User.Identity.IsAuthenticated)
            {
                var authent = ((ClaimsIdentity)User.Identity).Claims.FirstOrDefault () ;
                if (authent != null)
                {
                    id = authent.Value.ToString();
                }
            }
           
            var usuario =  _usuarioRepositorio.PegarUsuarioPeloId  (id);
            var fornecedor = usuario.Result.Fornecedor; //"IUS NATURA LTDA";
            var idStatusVigencia = 3;

            List<ProcessoViewModel> viewModel = new List<ProcessoViewModel>();
            foreach (var item in _processoRepositorio.RetornarProcessosPorFornecedor(idStatusVigencia, fornecedor))
            {
                ProcessoViewModel model = new ProcessoViewModel()
                {
                    Apolice = item.TIPO_APOLICE,
                    Clausula = item.DS_CLAUSULA,
                    DataInicio = item.DT_CRIACAO,
                    Contrato = item.NR_CONTRATO,
                    Empresa = item.EMPRESA
                };
                viewModel.Add(model);
            }
            return View(viewModel);
        }
    }
}

FlowGestaoContrato/Controllers/UsuariosController.cs
using FlowGestaoContrato.Models;
using FlowGestaoContrato.Interfaces;
using FlowGestaoContrato.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FlowGestaoContrato.Repositories;
using Microsoft.Extensions.Configuration;
using System.Net.Mail;

namespace FlowGestaoContrato.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly IFuncaoRepositorio _funcaoRepositorio;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IContatoFornecedorRepositorio _contatoFornecedor;
        private readonly IConfiguration _configuration;

        public UsuariosController(IUsuarioRepositorio usuarioRepositorio
            , IFuncaoRepositorio funcaoRepositorio
            , IWebHostEnvironment webHostEnvironment
            , IContatoFornecedorRepositorio contatoFornecedor
            , IConfiguration configuration)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _funcaoRepositorio = funcaoRepositorio;
            _webHostEnvironment = webHostEnvironment;
            _contatoFornecedor = contatoFornecedor;
            _configuration = configuration;
        }

        /// <summary>
        /// TO-DO não é pegar todos e sim trazer os processos
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Administrador,Fornecedor")]
        public IActionResult Index()
        {
            return View();
            //return View(await _usuarioRepositorio.PegarTodos());
            //Task<IActionResult> 
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Login()
        {
            if (User.Identity.IsAuthenticated)
                await _usuarioRepositorio.DeslogarUsuario();

            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                Usuario usuario = await _usuarioRepositorio.PegarUsuarioPeloEmail(model.Email);
                if (usuario != null)
                {
                    if (usuario.PrimeiroAcesso == true)
                    {
                        // Redirecionar Redefinir senha
                        return RedirectToAction(nameof(RedefinirSenha));
                    }
                    else
                    {
                        PasswordHasher<Usuario> passwordHasher = new PasswordHasher<Usuario>();
                        if (passwordHasher.VerifyHashedPassword(usuario, usuario.PasswordHash, model.Senha) != PasswordVerificationResult.Failed)
                        {
                            await _usuarioRepositorio.LogarUsuario(usuario, false);

                            if (await _usuarioRepositorio.VerificarSeUsuarioEstaEmFuncao(usuario, "Fornecedor"))
                                return RedirectToAction(nameof(Index));
                            else if (await _usuarioRepositorio.VerificarSeUsuarioEstaEmFuncao(usuario, "Administrador"))
                                return RedirectToAction(nameof(Index));
                            else
                                return RedirectToAction(nameof(AcessoNegado));
                        }
                        else
                        {
                            ModelState.AddModelError("", "Usuario e/ou senhas inválidos");
                            return View(model);
                        }
                    }
                }
                else
                {
                    // Criar usaurio com a 1. senha CNPJ
                    var emailFornValidao = _contatoFornecedor.RetornarProcessosPorFornecedor(model.Email, model.Senha);
                    if (emailFornValidao != null)
                    {
                        Usuario novoUsuario = new Usuario();
                        IdentityResult usuarioCriado;

                        model.Senha = _usuarioRepositorio.CodificarSenha(usuario, model.Senha);
                        novoUsuario.UserName = emailFornValidao.NM_CNTAT;
                        novoUsuario.PasswordHash = model.Senha;
                        novoUsuario.PrimeiroAcesso = true;
                        novoUsuario.CNPJ = emailFornValidao.CD_CPF_CNPJ;
                        novoUsuario.Email = model.Email;
                        novoUsuario.Status = StatusConta.Analisando;
                        novoUsuario.Fornecedor = emailFornValidao.NM_FANTS;
                        usuarioCriado = await _usuarioRepositorio.CriarUsuario(novoUsuario, model.Senha);

                        if (usuarioCriado.Succeeded)
                        {
                            return RedirectToAction(nameof(RedefinirSenha), model);
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "Email/Senha do primeiro acesso do usuário está invalido.");
                        return View(model);
                    }
                }
            }

            return View(model);

        }

        /// <summary>
        /// OK - TODO por email
        /// </summary>
        /// <param name="usuario"></param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public IActionResult RedefinirSenha(Usuario usuario)
        {
            TrocaSenhaViewModel model = new TrocaSenhaViewModel
            {
                Email = usuario.Email
            };

            return View(model);
        }

        /// <summary>
        /// OK - TODO por email
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> RedefinirSenha(TrocaSenhaViewModel model)
        {
            if (ModelState.IsValid)
            {
                Usuario usuario = await _usuarioRepositorio.PegarUsuarioPeloEmail(model.Email);
                model.Senha = _usuarioRepositorio.CodificarSenha(usuario, model.Senha);
                usuario.PasswordHash = model.Senha;
                usuario.PrimeiroAcesso = false;
                usuario.Status = StatusConta.Aprovado;
                await _usuarioRepositorio.AtualizarUsuario(usuario);
                await _usuarioRepositorio.IncluirUsuarioEmFuncao(usuario, "Fornecedor");
                await _usuarioRepositorio.LogarUsuario(usuario, false);                

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        /// <summary>
        /// TO-DO - Layout
        /// </summary>
        /// <returns></returns>
        public IActionResult AcessoNegado()
        {
            return View();
        }

        /// <summary>
        /// TO-DO - Layout
        /// </summary>
        /// <returns></returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _usuarioRepositorio.DeslogarUsuario();
            return RedirectToAction(nameof(Login));
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult EsqueceuSenha()
        {
            return View();
        }

        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult EsqueceuSenha(EsqueceuSenhaViewModel emailEnvio)
        {
            EsqueceuSenhaViewModel model = new EsqueceuSenhaViewModel
            {
                Email = emailEnvio.Email
            };

            // email não esta esta cadstrado p/ usuario 
            Task<Usuario> usuario = _usuarioRepositorio.PegarUsuarioPeloEmail(model.Email);

            if (usuario.Result != null)
            {
                // Zera pimeiro acesso e resetar senha para o CNPJ
                usuario.Result.EmailConfirmed = true;
                usuario.Result.PrimeiroAcesso = true;
                usuario.Result.Status = StatusConta.Analisando;
                _usuarioRepositorio.AtualizarUsuario(usuario.Result);

                // Envia email com o link para trocar
                // Busca valores de configurações                
                var mailAddress = _configuration.GetSection("SmtpConfigurations")["Sender"];
                var mailPassword = _configuration.GetSection("SmtpConfigurations")["Password"];
                var mailHost = _configuration.GetSection("SmtpConfigurations")["Host"];
                var mailPort = _configuration.GetSection("SmtpConfigurations")["Port"];

                var linkResetSenha = _configuration.GetSection("Parametros")["LinkResetSenha"];

                // Busca lista de pessoas que irão receber e-mail
                var listToSendMail = model.Email;

                // Monta corpo do e-mail
                string strCorpoMensagem = "<table style='width:100%;font-family: Trebuchet MS, Arial, Helvetica, sans-serif;border-collapse: collapse;font-size:80%;border: 0px solid #dddddd;padding: 4px;' border='1px'>";

                // Insere imagem
                strCorpoMensagem += "<tr>";
                strCorpoMensagem += "<td colspan=3 style='border:0px;text-align:left;padding-left:5px;'><img src='enevalogo.png' width=50></td>";
                strCorpoMensagem += "</tr>";

                // Informação
                strCorpoMensagem += "<tr>";

FlowGestaoContrato/Views/Shared/_BoasVindas.cshtml
@using Microsoft.AspNetCore.Identity
@using FlowGestaoContrato.Models
@using FlowGestaoContrato.Interfaces

@inject SignInManager<Usuario> _gerenciadorLogin
@inject UserManager<Usuario> _gerenciadorUsuarios
@inject IUsuarioRepositorio _usuarioRepositorio

@{
    Usuario usuario = await _usuarioRepositorio.PegarUsuarioPeloNome(User);
    IList<string> funcoes = await _usuarioRepositorio.PegarFuncoesUsuario(usuario);
}

@if (_gerenciadorLogin.IsSignedIn(User))
{
    <ul>
        <li>
            <a class="nav-link white-text">Olá, @usuario.UserName</a>
        </li>

        <li>
            <a class="nav-link white-text">@usuario.Email</a>
        </li>

        <li>
            @foreach(string funcao in funcoes)
            {
                <a class="nav-link white-text">@funcao</a>
            }
        </li>

        <li>
            <a class="nav-link white-text">Bem vindo ao FLOW</a>
        </li>
        
    </ul>
}

FlowGestaoContrato/Views/Shared/_Confirmacoes.cshtml
@if (TempData["NovoRegistro"] != null)
{
    <div class="card-panel green darken-3 valign-wrapper white-text">
        <div class="col s1">
            <i class="material-icons">check_box</i>
        </div>

        <div class="col s11">
            @TempData["NovoRegistro"].ToString()
        </div>
    </div>
}


@if (TempData["Atualizacao"] != null)
{
    <div class="card-panel blue darken-3 valign-wrapper white-text">
        <div class="col s1">
            <i class="material-icons">check_box</i>
        </div>

        <div class="col s11">
            @TempData["Atualizacao"].ToString()
        </div>
    </div>
}

@if (TempData["Exclusao"] != null)
{
    <div class="card-panel red darken-3 valign-wrapper white-text">
        <div class="col s1">
            <i class="material-icons">check_box</i>
        </div>

        <div class="col s11">
            @TempData["Exclusao"].ToString()
        </div>
    </div>
}

FlowGestaoContrato/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlowGestaoContrato</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <div class="row">
        <div class="col s3">
            @if (User.Identity.IsAuthenticated)
            {
                <partial name="_SideNav" />}
        </div>

        <div class="col s9">
            @if (User.Identity.IsAuthenticated)
            {
                <partial name="_Nav" />}

            <div class="conteudo-principal">
                <div class="body-content">
                    @RenderBody()
                    <hr />
                    <footer>
                        <div class="container">
                            &copy; FLOW
                        </div>
                    </footer>
                </div>
            </div>
        </div>
    </div>


    <environment include="Development">
        <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.js"></script>
        <script src="~/js/InicializarTooltips.js"></script>
        <script>
            $(document).ready(function () {
                $('.sidenav').sidenav({});
            })
        </script>
        @RenderSection("Scripts", required: false)
    </environment>

    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js"></script>
        <script src="~/js/InicializarTooltips.js"></script>
        <script>
            $(document).ready(function () {
                $('.sidenav').sidenav({});
            })
        </script>
        @RenderSection("Scripts", required: false)
    </environment>

    @*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FlowGestaoContrato</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@
    @*<div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>*@

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FlowGestaoContrato - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@

    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)*@
</body>
</html>

FlowGestaoContrato/Views/Shared/_Logout.cshtml
@using Microsoft.AspNetCore.Identity
@using FlowGestaoContrato.Models
@inject SignInManager<Usuario> SignInManager

@if(SignInManager.IsSignedIn(User))
{
    <form asp-action="Logout" asp-controller="Usuarios" id="formularioLogout">
        <ul>
            <li>
                <a class="nav-link white-text" style="cursor:pointer;" onclick="document.getElementById('formularioLogout').submit();">Logout</a>
            </li>
        </ul>

    </form>
}

FlowGestaoContrato/Views/Shared/_ModalExcluir.cshtml
<div class="modal modal-fixed-footer" id="modal">
    <div class="modal-content">
        <h6>Exclusão de registros</h6>
        <p>Prosseguir com a exclusão de <text class="nome"></text> ?</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn-small red darken-4 btnExcluir">Sim</button>
        <button type="button" class="btn-small blue darken-4 modal-close">Não</button>
    </div>
</div>

FlowGestaoContrato/Views/Shared/_Nav.cshtml
<nav class="grey darken-3">
    <div class="nav-wrapper navbar-fixed">
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            @*<li class="nav-item"><a class="nav-link" asp-controller="Usuarios" asp-action="MinhasInformacoes">Minhas Informações</a></li>*@
            <li class="nav-item"><partial name="_Logout" /></li>
        </ul>
    </div>
</nav>

FlowGestaoContrato/Views/Shared/_SideNav.cshtml
@using Microsoft.AspNetCore.Identity
@using FlowGestaoContrato.Models
@using FlowGestaoContrato.Interfaces

@*@inject SignInManager<Usuario> _gerenciadorLogin*@
@*@inject UserManager<Usuario> _gerenciadorUsuarios*@
@inject IUsuarioRepositorio _usuarioRepositorio

@{

    Usuario usuario = await _usuarioRepositorio.PegarUsuarioPeloNome(User);
}

<ul id="slide-out" class="sidenav sidenav-fixed">
    <li class="center-align">
        <div class="user-view">
            <div class="background purple darken-4">

            </div>
            <text> <partial name="_BoasVindas" /></text>
        </div>
    </li>

    @*@if (await _usuarioRepositorio.VerificarSeUsuarioEstaEmFuncao(usuario, "Administrador") || await _usuarioRepositorio.VerificarSeUsuarioEstaEmFuncao(usuario, "Gestor"))
    {
        <li class="nav-item"><a class="nav-link" asp-controller="Dashboard" asp-action="Index"><i class="material-icons">insert_chart</i> Dashboard</a></li>
        <li class="nav-item"><a class="nav-link" asp-controller="Usuarios" asp-action="Index"><i class="material-icons">account_box</i> Usuarios</a></li>
        <li class="nav-item"><a class="nav-link" asp-controller="Apartamentos" asp-action="Index"><i class="material-icons">store</i> Apartamentos</a></li>
        <li class="nav-item"><a class="nav-link" asp-controller="Alugueis" asp-action="Index"><i class="material-icons">attach_money</i>Alugueis</a></li>
    }
    
    @if (await _usuarioRepositorio.VerificarSeUsuarioEstaEmFuncao(usuario, "Administrador"))
    {
        <li class="nav-item"><a class="nav-link" asp-controller="Funcoes" asp-action="Index"><i class="material-icons">group</i>Funções</a></li>
    }*@

    <li class="nav-item"><a class="nav-link" asp-controller="Processo" asp-action="Index"><i class="material-icons">settings</i>Processos</a></li>
    @*<li class="nav-item"><a class="nav-link" asp-controller="Eventos" asp-action="Index"><i class="material-icons">list</i>Eventos</a></li>
    <li class="nav-item"><a class="nav-link" asp-controller="Servicos" asp-action="Index"><i class="material-icons">settings</i> Serviços</a></li>*@
</ul>